theme: minima
title: My School Of English
description: Szkoła języka angielskiego w Bytomiu


collections:
  pages:
    output: true


header_pages:
  - _pages/oferta.md
  - _pages/warsztaty.md
  - _pages/cennik.md
  - _pages/kadra.md
  - _pages/kontakt.md

footer_pages:
  - _pages/standardy-ochrony.md
  - _pages/polityka-plikow-cookies.md
  - _pages/kontakt.md

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - Dockerfile
  - docker-compose.yml

