theme: minima
title: My School Of English
description: Szkoła języka angielskiego w Bytomiu
lang: pl-PL

collections:
  pages:
    output: true

permalink: /blog/:year/:month/:day/:title/
minima:
  date_format: "%Y-%m-%d"

header_pages:
  - _pages/oferta.md
  - _pages/warsztaty.md
  - _pages/cennik.md
  - _pages/kadra.md
  - _pages/kontakt.md

footer_pages:
  - _pages/standardy-ochrony.md
  - _pages/polityka-plikow-cookies.md
  - _pages/blog.md
  - _pages/kontakt.md

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - Dockerfile
  - docker-compose.yml
